name = "MyJuliaExample"
uuid = "c5d1bf38-ce54-4138-8be9-f95ec06bea48"
authors = ["SAKAI Yoshiki <sakai@sakaiyoshiki.dev>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
julia = "1.10"
